name       : godot-headers
version    : 3.4.4
release    : 3
source     :
    - https://github.com/godotengine/godot-headers/archive/refs/tags/godot-3.4.4-stable.tar.gz : bb0eac00a4d5b800a4ca2555d11b4a35981bdb730b630e9bd31a0649fa1d6fd7
license    : MIT
component  : programming.devel
summary    : Headers for the Godot API supplied by the GDNative module
description: |
    GDNative enables the use of dynamically linked libraries inside of Godot.
    NativeScript uses GDNative to implement scripts backed by native code.
rundeps    :
    - godot-common
setup      : |
    sed "s/@VERSION@/%version%/" $pkgfiles/godot.pc.in > godot.pc
install    : |
    install -dm00755 $installdir/usr/include/godot
    install -Dm00644 godot.pc $installdir/usr/lib64/pkgconfig/godot.pc
    rm -rf *.md images
    cp -rup * $installdir/usr/include/godot
patterns   :
    - /*
