name       : godot-headers
version    : 3.5.1
release    : 6
source     :
    - https://github.com/godotengine/godot-headers/archive/refs/tags/godot-3.5.1-stable.tar.gz : 1c38268031425a4881c0d6d41926a0f1bf5847f05dc24c29332609e318276b6b
license    : MIT
component  : programming.devel
summary    : Headers for the Godot API supplied by the GDNative module
description: |
    GDNative enables the use of dynamically linked libraries inside of Godot.
    NativeScript uses GDNative to implement scripts backed by native code.
rundeps    :
    - godot-common
setup      : |
    sed "s/@VERSION@/%version%/" $pkgfiles/godot.pc.in > godot.pc
install    : |
    install -dm00755 $installdir/usr/include/godot
    install -Dm00644 godot.pc $installdir/usr/lib64/pkgconfig/godot.pc
    rm -rf *.md images
    cp -rup * $installdir/usr/include/godot
patterns   :
    - /*
